### ISSUE TITLE
Not working with .net core console application dlls.

### ISSUE THREAD

**Issue by kiranbchitari** [XenocodeRCE/neo-ConfuserEx#23]
I am trying obfuscating .net core dll but it is not able to do that. It is showing an error: 
[ERROR] Failed to resolve dependency of 'DemoApp.dll'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: System.Console, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in G:\Users\Xenocode\Source\Repos\neo-ConfuserEx\dnlib\src\DotNet\IAssemblyResolver.cs:line 114
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in G:\Users\Xenocode\Source\Repos\neo-ConfuserEx\Confuser.Core\ConfuserEngine.cs:line 267
Failed at 11:38 AM, 0:00 elapsed.

**Comment by EmoxypineRCE** [comment]
Confuser not found DemoApp.dll. Add DemoApp in folder with project
