### ISSUE TITLE
Failed to protect exe file that have Embedded Resource dll file.

### ISSUE THREAD

**Issue by alpakeno** [XenocodeRCE/neo-ConfuserEx#27]
[ERROR] Failed to resolve dependency of 'filename.exe'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: testlib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in G:\Users\Xenocode\Source\Repos\neo-ConfuserEx\dnlib\src\DotNet\IAssemblyResolver.cs:line 114
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in G:\Users\Xenocode\Source\Repos\neo-ConfuserEx\Confuser.Core\ConfuserEngine.cs:line 267
Failed at 6:30 PM, 0:00 elapsed.

**Comment by alpakeno** [comment]
OK, it works if the dll files is in the same folder as the exe file.
