### ISSUE TITLE
Failed to resolve dependency of DLL

### ISSUE THREAD

**Issue by gumbof0125** [XenocodeRCE/neo-ConfuserEx#49]
I am using VS2017, my Clickonce project's target framework is .Net Framework 4.5, and using ConfuserEx v1.0.0-custom now.

Now I want to publish my project as Clickonce with confusion (including all referenced file, that mean assembly). 
Step for my case: 
1. Choose "Release build"
2. Then confuse the output files (.exe and all .dll) from Release folder
3. Select Preset as "Minimum" as rules only
3. During the confusion, "LabCI.TA4CS.Chart.dll" must occur "Failed to resolve dependency of xx.dll" problem. 

I don't know how to solve it. And I try to embed it into my .exe or make it don't be confused (But don't know whether work or not). So, Does ConfuseEX have any feature, coding or way as solution, or any other way to exclude this .dll file or embed it into .exe? 

The error is shown below:
[ERROR] Failed to resolve dependency of 'LabCI.TA4CS.Chart.dll'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: WPFVisifire.Charts, Version=2.2.3.0, Culture=neutral, PublicKeyToken=99d724542e4db593
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in C:\Gary\Project\TempFile\190416_ResearchOfConfuser\ConfuserEx-master\ConfuserEx-master\dnlib\src\DotNet\IAssemblyResolver.cs:line 114
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in C:\Gary\Project\TempFile\190416_ResearchOfConfuser\ConfuserEx-master\ConfuserEx-master\Confuser.Core\ConfuserEngine.cs:line 267
Failed at 9:23 AM, 0:00 elapsed.

**Comment by XenocodeRCE** [comment]
Include the file WPFVisifire.Charts.dll in the same directory as LabCI.TA4CS.Chart.dll

**Comment by wozs** [comment]
> Include the file WPFVisifire.Charts.dll in the same directory as LabCI.TA4CS.Chart.dll

Thank you it worked.
Just put the .dll the program cant find where you set the base directory.
