### ISSUE TITLE
Service Crashes at start if used Neo-ConfuserEx

### ISSUE THREAD

**Issue by amoltarte** [XenocodeRCE/neo-ConfuserEx#67]
**Describe the bug**
I have a Windows Service.
I build it in release mode and obfuscate it using Neo-ConfuserEx.
The service installs but fails to start.

Settings as below...

<project outputDir="D:\git\cch24\LMSCCH24\bin\Release\Confused" baseDir="D:\git\cch24\LMSCCH24\bin\Release" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="maximum" />
  <module path="LMSCCH24.exe">
    <rule pattern="true" preset="maximum" inherit="false">
      <protection id="anti ildasm" />
      <protection id="anti tamper" />
      <protection id="constants" />
      <protection id="anti dump" />
      <protection id="anti debug" />
      <protection id="invalid metadata" />
      <protection id="ref proxy" />
      <protection id="resources" />
      <protection id="rename" />
    </rule>
  </module>
</project>

**Expected behavior**
Service should start as if it is not obfuscated.

**Screenshots**
![Neoconfuser1](https://user-images.githubusercontent.com/8025714/107499272-c2ba2400-6bba-11eb-8c2e-85a07cd911f9.jpg)

![Neoconfuser2](https://user-images.githubusercontent.com/8025714/107499221-b1711780-6bba-11eb-9c6d-ca551da80b01.jpg)

**Comment by Scortchhh** [comment]
can you check if its a fatal error, in windows event viewer?

**Comment by amoltarte** [comment]
Yes. There is an error in Event Viewer.

**Application Log**
========================================

Service cannot be started. System.NullReferenceException: Object reference not set to an instance of an object.
   at ⁯⁯⁯‍‌⁭‎‮⁫‌⁬‪‎‬‮‏⁮‍‌‎⁪‪‫​‎⁪‍‮‌​⁪⁮⁪‫⁬⁬‪⁫⁮⁭‮.‮‮‮‪‏‫⁪‫⁫⁮​⁪‍⁯‭⁫⁬⁮⁫‏⁫‪‬‏⁬‌‮‮‌⁯⁮‏‫​‎‫‌⁬⁫⁯‮()
   at System.ServiceProcess.ServiceBase.DeferredStop()
   at ⁯⁯⁯‍‌⁭‎‮⁫‌⁬‪‎‬‮‏⁮‍‌‎⁪‪‫​‎⁪‍‮‌​⁪⁮⁪‫⁬⁬‪⁫⁮⁭‮.​‏‏‫‍‪‪⁮⁯⁮‪‮⁭‌⁮‪⁯⁮‎‭‏‌⁫‪⁪‪⁭⁯‍‮⁫⁯‍⁬‮​⁮‮‬‌‮(String[] )
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

**System**
=======================================
The LogicMoCCH24 service terminated with the following error: 
An exception occurred in the service when handling the control request.


I know what "Object Reference Not Set To An Instance" means, but these errors are not thrown if not Obfuscated.

Please help... let me know if any additional steps are needed to change in code to use obfuscation (Neo-Obfuscator)
I am desperately in need.

--
